name: Auto-create Version Tag

on:
  push:
    branches:
      - main # Define the branch where you want to create tags
      - '*' # Trigger for all branches

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=LATEST_TAG::$(git describe --abbrev=0 --tags)"

      - name: Generate version tag
        id: version_tag
        run: |
          branch_name="${{ steps.branch_name.outputs.BRANCH_NAME }}"
          latest_tag="${{ steps.latest_tag.outputs.LATEST_TAG }}"

          if [[ "$branch_name" == "main" ]]; then
            # Increment patch version for main branch
            version=$(echo "$latest_tag" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          else
            # Use branch name as version
            version="v1.0.0-$branch_name"
          fi

          echo "::set-output name=VERSION_TAG::$version"

      - name: Create version tag
        if: steps.version_tag.outputs.VERSION_TAG != ''
        run: |
          version_tag="${{ steps.version_tag.outputs.VERSION_TAG }}"
          git tag "$version_tag"
          git push origin "$version_tag"
